### ISSUE TITLE
pluralith login of v0.2.2 release fails 

### ISSUE THREAD

**Issue by mhsFlairs** [Pluralith/pluralith-cli#122]
Running inside docker ubuntu contaienr. 
when trying to login pluralith using pluralith_cli_linux_amd64_v0.2.2 binary. It fails throwing the following exception 

```
> [5/6] RUN pluralith login --api-key 2d00e27caa484649411d53447e2b1409:
#0 30.53 panic: runtime error: invalid memory address or nil pointer dereference
#0 30.53 [signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x7e68b9]
#0 30.53 
#0 30.53 goroutine 1 [running]:
#0 30.53 pluralith/pkg/install.GetGitHubRelease({0x1116254, 0x37}, 0xc0006bfd30?, {0x0, 0x0}, 0x1)
#0 30.53        /Users/dan/Code/GoProjects/src/github.com/dantheputzer/pluralith-cli/app/pkg/install/GetGitHubRelease.go:38 +0x3b9
#0 30.53 pluralith/pkg/install/components.GraphModule(0x60?)
#0 30.53        /Users/dan/Code/GoProjects/src/github.com/dantheputzer/pluralith-cli/app/pkg/install/components/GraphModule.go:35 +0x211
#0 30.53 main.initApp()
#0 30.53        /Users/dan/Code/GoProjects/src/github.com/dantheputzer/pluralith-cli/app/main.go:32 +0x31e
#0 30.53 main.main()
#0 30.53        /Users/dan/Code/GoProjects/src/github.com/dantheputzer/pluralith-cli/app/main.go:42 +0x17
```

When downgraded to 0.2.1, the setup was successful

**Comment by mhsFlairs** [comment]
Reproducing by running the following go script in a docker ubuntu 

```
package main

import (
	"fmt"
	"runtime"
    "encoding/json"
	"io"
	"net/http"

)

func main() {

	fmt.Println("Hello, World!")

	myOS, myArch := runtime.GOOS, runtime.GOARCH

	fmt.Printf("I'm running on %s/%s.\n", myOS, myArch)

	url := "https://api.pluralith.com/v1/dist/download/cli/graphing"

	params := map[string]string{"os": myOS, "arch": myArch}

	request, _ := http.NewRequest("GET", url, nil)

	request.Header.Add("Authorization", "Bearer 2d00e27caa484649411d53447e2b1409")

	queryString := request.URL.Query()

	for paramKey, paramValue := range params {
		queryString.Add(paramKey, paramValue)
	}

	request.URL.RawQuery = queryString.Encode()

	// Execute get version request
	client := &http.Client{}

	response, responseErr := client.Do(request)

	fmt.Println(response)

	fmt.Println(responseErr)

	var bodyObject map[string]interface{}

	bodyBytes, _ := io.ReadAll(response.Body)

	parseErr := json.Unmarshal(bodyBytes, &bodyObject)

	if parseErr != nil {
		fmt.Errorf("parsing response failed ")
		return
	}

	if responseErr != nil || response.StatusCode != 200 {
		fmt.Errorf("fetching latest version failed")
		return
	}

	versionData := bodyObject["data"].(map[string]interface{})

	var currentVersionString string
	var currentVersion string
	var successMessage string

	// Handle non-existent version
	if len(currentVersionString) > 0 {
		currentVersion = currentVersionString
		successMessage = "A new version is available!"
	} else {
		currentVersion = "0.0.0"
		currentVersionString = "None"
		successMessage = "No graph module installed, found latest release"
	}

	latestVersion, _ := versionData["version"].(string)

	fmt.Println(successMessage)
	fmt.Printf("Current version: %s\n", currentVersion)
	fmt.Printf("Latest version: %s\n", latestVersion)

}
```

it revealed that it's a connection issue returning connection refused or x509: certificate signed by unknown authority. But it wasn't handled.

Adding a check if responseErr != nil before ReadAll(response.Body), fixed the invalid memory address or nil pointer dereference and revealed the true issue
