### ISSUE TITLE
Graphing issue

### ISSUE THREAD

**Issue by SamCrudge** [Pluralith/pluralith-cli#47]
Hello,

When trying to build a graph it has failed on multiple projects when using the CLI

CLI Version: 0.1.11
Graph Module Version: 0.1.8
UI Version: 0.1.12

I've tried in Test mode and without.

I've ran every command given in the Docs but it still fails.

Before running the command below i ensured a local terraform plan and state was built.

Error:
```pluralith run --var-file var/client-staging.tfvars 
⠿ Initiating Run ⇢ Posting To Pluralith Dashboard
 → Branch detected: master

→ Verify
  ✔ API key is valid, you are authenticated!
  ✔ Project ID is valid!

→ Plan
  ✔ Execution Plan Generated
  ✔ Secrets Stripped
  - Cost Calculation Skipped

→ Export
  ✘ Diagram Generation Failed
pluralith-cli-graphing graph

Render graph and export PDF

Options:
  --help     Show help                                                 [boolean]
  --version  Show version number                                       [boolean]

RangeError: Maximum call stack size exceeded
    at Function.entries (<anonymous>)
    at _0x476093.GetObjectsByKeyRec (<anonymous>:1:593342)
    at _0x476093.GetObjectsByKeyRec (<anonymous>:1:593644)
    at _0x476093.GetObjectsByKeyRec (<anonymous>:1:593644)
    at _0x476093.GetObjectsByKeyRec (<anonymous>:1:593644)
    at _0x476093.GetObjectsByKeyRec (<anonymous>:1:593644)
    at _0x476093.GetObjectsByKeyRec (<anonymous>:1:593644)
    at _0x476093.GetObjectsByKeyRec (<anonymous>:1:593644)
    at _0x476093.GetObjectsByKeyRec (<anonymous>:1:593644)
    at _0x476093.GetObjectsByKeyRec (<anonymous>:1:593644)

generating diagram failed -> RunGraph: running CLI command failed -> GenerateDiagram: exit status 1
  ✘ Posting Run To Pluralith Dashboard Failed
reading cache from disk failed -> HandleCIRun: open /aws-terraform-client/.pluralith/pluralith.cache.json: no such file or directory```

**Comment by DanThePutzer** [comment]
Hi Sam,

Thanks for opening up the issue! Seems like an issue with the graphing module. From what I see it fails on the headless pdf export. When you run `pluralith plan` do you get any output in the desktop app or does it also fail there?

**Comment by SamCrudge** [comment]
I get a failed to graph error there too, but when I hit export error it asks me to open a file rather than save one via the UI.

Cheers for speedy response!

**Comment by DanThePutzer** [comment]
Alright it seems like that is an issue with the graphing algorithm then. Would you be open to run `pluralith strip` on one of the failing projects (preferably the most complex one), inspect the output and share it with us if you deem it safe? The `strip` command hashes everything in the state except for the relationships between resources. This way @PhiWeber can debug the graphing on an anonymised and stripped state, making things much faster.

**Comment by DanThePutzer** [comment]
@SamCrudge I think this specific issue got resolved, so I'ma go ahead and close it :)

**Comment by AnasAbdelhakam** [comment]
having same issue with some projects only 
any  ideas 
```pluralith graph --var-file test.tfvars --local-only --out-dir /home/ubuntu/wesam --file-name retail-test --title retial-test
parsing response failed -> GetGitHubRelease: %!w(<nil>)
⠿ Initiating Graph ⇢ Posting Diagram To Pluralith Dashboard

→ Authentication
  ✔ API key is valid, you are authenticated!

→ Plan
  ✔ Local Execution Plan Generated
  ✔ Local Plan Cache Created
  ✔ Secrets Stripped
  - Cost Calculation Skipped

→ Graph
  ✘ Local Diagram Generation Failed
pluralith-cli-graphing graph

Render graph and export PDF

Options:
  --help     Show help                                                 [boolean]
  --version  Show version number                                       [boolean]

RangeError: Maximum call stack size exceeded
    at new Cr (/snapshot/pluralith-cli-graphing/node_modules/@Pluralith/pluralith-export/dist/bundle/pluralith-export.bundle.js:2:23051)
    at dt.children (/snapshot/pluralith-cli-graphing/node_modules/@Pluralith/pluralith-export/dist/bundle/pluralith-export.bundle.js:2:27338)
    at dt.each (/snapshot/pluralith-cli-graphing/node_modules/@Pluralith/pluralith-export/dist/bundle/pluralith-export.bundle.js:2:27602)
    at dt.writeDataToDom (/snapshot/pluralith-cli-graphing/node_modules/@Pluralith/pluralith-export/dist/bundle/pluralith-export.bundle.js:2:29199)
    at dt.writeDataToDom (/snapshot/pluralith-cli-graphing/node_modules/@Pluralith/pluralith-export/dist/bundle/pluralith-export.bundle.js:2:32091)
    at dt.xml (/snapshot/pluralith-cli-graphing/node_modules/@Pluralith/pluralith-export/dist/bundle/pluralith-export.bundle.js:2:29347)
    at dt.svg (/snapshot/pluralith-cli-graphing/node_modules/@Pluralith/pluralith-export/dist/bundle/pluralith-export.bundle.js:2:28979)
    at r.<anonymous> (/snapshot/pluralith-cli-graphing/node_modules/@Pluralith/pluralith-export/dist/bundle/pluralith-export.bundle.js:2:2524743)
    at /snapshot/pluralith-cli-graphing/node_modules/@Pluralith/pluralith-export/dist/bundle/pluralith-export.bundle.js:2:2506849
    at Object.next (/snapshot/pluralith-cli-graphing/node_modules/@Pluralith/pluralith-export/dist/bundle/pluralith-export.bundle.js:2:2506954)

generating diagram failed -> GenerateGraph: running CLI command failed -> GenerateDiagram: exit status 1
```
