### ISSUE TITLE
Invalid character in header content ["authorization"]

### ISSUE THREAD

**Issue by CloudMarshall** [Pluralith/pluralith-cli#66]
Error performing pluralith graph:

TypeError [ERR_INVALID_CHAR]: Invalid character in header content ["authorization"]
    at ClientRequest.setHeader (node:_http_outgoing:579:3)
    at new ClientRequest (node:_http_client:262:14)
    at Object.request (node:https:353:10)
    at RedirectableRequest._performRequest (/snapshot/pluralith-cli-graphing/node_modules/follow-redirects/index.js:279:24)
    at new RedirectableRequest (/snapshot/pluralith-cli-graphing/node_modules/follow-redirects/index.js:61:8)
    at Object.request (/snapshot/pluralith-cli-graphing/node_modules/follow-redirects/index.js:487:14)
    at dispatchHttpRequest (/snapshot/pluralith-cli-graphing/node_modules/axios/lib/adapters/http.js:242:25)
    at new Promise (<anonymous>)
    at httpAdapter (/snapshot/pluralith-cli-graphing/node_modules/axios/lib/adapters/http.js:48:10)
    at dispatchRequest (/snapshot/pluralith-cli-graphing/node_modules/axios/lib/core/dispatchRequest.js:58:10) {
  code: 'ERR_INVALID_CHAR'

Running in WSL - Ubuntu 20.04.5

within ~/Pluralith/credentials is my API key.

**Comment by CloudMarshall** [comment]
Hi @DanThePutzer 

Just updated and worked a treat - thanks very much for the quick turnaround!

👍

**Comment by DanThePutzer** [comment]
Awesome!

Also, any feedback on the looks of the diagram is welcome! We're always trying to improve that side of things as well :)
